name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: my_database
          MYSQL_USER: my_user
          MYSQL_PASSWORD: my_password
        options: > 
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies via Composer
      run: composer install

    - name: Set up Apache
      run: sudo apt-get install apache2 -y

    - name: Start MySQL service
      run: sudo service mysql start

    - name: Configure database
      run: |
        mysql -u root -proot_password -e "CREATE DATABASE IF NOT EXISTS my_database;"
        mysql -u root -proot_password -e "CREATE USER IF NOT EXISTS 'my_user'@'localhost' IDENTIFIED BY 'my_password';"
        mysql -u root -proot_password -e "GRANT ALL PRIVILEGES ON my_database.* TO 'my_user'@'localhost';"
        mysql -u root -proot_password -e "FLUSH PRIVILEGES;"

    - name: Deploy Application
      run: |
        sudo cp -r . /var/www/html/
        sudo chown -R www-data:www-data /var/www/html/
        sudo systemctl restart apache2
